# This make the data persistent.
volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: 'postgres:alpine'
    container_name: database
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    restart: 'always'
    ports:
      - "${DB_EXPOSED_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-test.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: debug
      ROOT_LOGLEVEL: info
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "6080:8080"
      - "9990:9990"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak: {}